web:
  build:
    context: .  # Change from ./webAppFrontend to .
    dockerfile: webAppFrontend/Dockerfile
  image: my-react-app
  ports:
    - "${WEB_PORT:-80}:${WEB_PORT:-80}"
  depends_on:
    - api
  environment:
    - PORT=${WEB_PORT:-80}
    - API_URL=http://api:5000
  networks:
    - app-network
  healthcheck:
    test: ["CMD", "curl", "--fail", "http://localhost:${WEB_PORT:-80}"]
    interval: 30s
    timeout: 10s
    retries: 3