services:
  api:
    build: ./backend
    image: my-flask-app
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    environment:
      - PORT=5000
    networks:
      - app-network
  web:
    build:
      context: ./webAppFrontend
    image: my-react-app
    ports:
      - "80:80"
    depends_on:
      - api
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network
networks:
  app-network:
    driver: bridge