services:
  api:
    build: ./backend
    image: my-flask-app
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    environment:
      - PORT=5000
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
  web:
    build:
      context: ./webAppFrontend
    image: my-react-app
    ports:
      - "${WEB_PORT:-80}:${WEB_PORT:-80}"
    depends_on:
      - api
    environment:
      - PORT=${WEB_PORT:-80}
      - API_URL=http://api:5000
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:${WEB_PORT:-80}"]
      interval: 30s
      timeout: 10s
      retries: 3
networks:
  app-network:
    driver: bridge