services:
  api:
    build: ./backend
    image: my-flask-app
    expose:
      - "5000"
    env_file:
      - ./backend/.env
    environment:
      - GUNICORN_CMD_ARGS=--workers=2 --threads=4 --timeout=120 --log-level=debug --bind=0.0.0.0:5000
    networks:
      - app-network

  web:
    build:
      context: ./webAppFrontend
    image: my-react-app
    ports:
      - "80:80"
    depends_on:
      - api
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge